---
# ===== k8s/deployment.yaml =====
apiVersion: v1
kind: Namespace
metadata:
  name: exnaton

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exnaton-api
  namespace: exnaton
  labels:
    app: exnaton-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exnaton-api
  template:
    metadata:
      labels:
        app: exnaton-api
    spec:
      containers:
      - name: api
        image: exnaton/api:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: url
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: exnaton-api-service
  namespace: exnaton
spec:
  selector:
    app: exnaton-api
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: exnaton-api-hpa
  namespace: exnaton
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exnaton-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: exnaton
type: Opaque
stringData:
  url: "postgresql://postgres:password@postgres-service:5432/exnaton"

---
# ===== k8s/postgres.yaml =====
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: exnaton
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: timescale/timescaledb:latest-pg14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "exnaton"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: exnaton
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
